### ISSUE TITLE
Not authenticated with oauth2

### ISSUE THREAD

**Issue by njmdietrich** [FliegendeWurst/naviki-gpx-download#1]
Hi,
I just tried to use your little script and am not sure whether I am doing something wrong or it is broken. I copied a string from a GET request that seems to have the right format for the oauth token, but when I run the script I get a key error for "ways" in the json dict (j) (line 26). Printing the contents of j reveals the following: 
{'exceptionClass': None, 'code': 5010, 'message': 'Not authenticated with oauth2.', 'errorUserTitle': None, 'errorUserMessage': None, 'traceId': None}
Unfortunately, I don't know enough about oauth to debug this further. Any hints?

**Comment by FliegendeWurst** [comment]
Hmm, perhaps Naviki changed their authentication scheme.. I'll have to investigate.

**Comment by FliegendeWurst** [comment]
Did you copy the entire authentication header (`Bearer XXXX....`)? The script only expects the last part (omitting the "Bearer " part).

In any case, I just pushed an update that will automatically detect this case and correct the issue. The download then works as expected for me.

**Comment by njmdietrich** [comment]
I think I  must have gotten the wrong header the last time. The authentication works now, but it can't extract the time from some titles. I might just add a timezone parameter to then calculate the time using the method suggested in the comment. Thank you for your help anyway!
